export const dailyPhrases = [
  'Cada foto cuenta una historia, cada instante guarda una emoción.',
  
  // --- Grupo 1: La Perspectiva y la Mirada ---
  'El lente revela aquello que el ojo humano frecuentemente decide ignorar.',
  'Un encuadre perfecto consiste simplemente en organizar el caos del universo visible.',
  'La cámara no captura el mundo, sino la forma en que eliges mirarlo.',
  'Mirar a través del visor es aislar una verdad en medio del ruido.',
  'La fotografía es el arte de enseñar a otros a observar su propio entorno.',
  'El espectador completa la obra cuando su mirada se cruza con la intención del autor.',
  'Cambiar de ángulo no solo altera la imagen, sino que transforma el significado entero.',
  'Lo que dejamos fuera del encuadre es tan importante como lo que decidimos incluir.',
  'El enfoque selectivo es una metáfora visual de nuestras propias prioridades vitales.',
  'Un retrato no documenta un rostro, sino la conexión efímera entre dos almas.',
  'La profundidad de campo nos enseña que no todo necesita estar claro para tener sentido.',
  'Cerrar un ojo para mirar por el visor es abrir el otro al interior.',
  'La composición es la sintaxis silenciosa con la que escribimos poemas visuales.',
  'Toda imagen es una ventana, pero también es un espejo de quien la dispara.',
  'El horizonte en una imagen es la frontera entre lo tangible y lo imaginado.',
  'A veces, el sujeto más fascinante es el espacio vacío que lo rodea.',
  'Capturar la escala de un paisaje es reconocer nuestra propia pequeñez en el mundo.',
  'La simetría nos da paz, pero la asimetría nos invita a hacernos preguntas profundas.',
  'Una lente gran angular expande el mundo, pero también nos hace vulnerables a su inmensidad.',
  'Mirar de cerca mediante la macrofotografía es descubrir universos enteros en una sola gota.',
  'La posición de la cámara dicta quién tiene el poder dentro de la narrativa visual.',
  'No fotografiamos lo que vemos, sino la forma en que sentimos lo observado.',
  'La perspectiva no es solo óptica, es una declaración absoluta de principios.',
  'El punto de fuga es el lugar donde nuestras certezas visuales finalmente desaparecen.',
  'Un plano cenital nos convierte en dioses observando un mundo que no podemos tocar.',
  'El contrapicado eleva al sujeto, otorgándole una grandeza que desafía nuestra propia altura.',
  'La mirada del sujeto a la cámara rompe la cuarta pared de nuestra indiferencia.',
  'Observar pacientemente es el verdadero trabajo; presionar el obturador es solo la consecuencia.',
  'La regla de los tercios existe para ser comprendida y, eventualmente, ser desafiada con propósito.',
  'Cada lente tiene su propia personalidad y reescribe la realidad a su manera.',
  'El ojo fotográfico se entrena reconociendo lo extraordinario dentro de la rutina más absoluta.',
  'No hay escenas aburridas, solo miradas que han olvidado cómo prestar verdadera atención.',
  'Una imagen sobrecargada ahoga el mensaje; la simplicidad visual exige mucha más valentía.',
  'El peso visual de un elemento puede desequilibrar por completo nuestras emociones.',
  'La textura en una fotografía es la manera en que el tacto se vuelve visual.',
  'El contraste no solo separa formas, sino que establece conflictos filosóficos en la imagen.',
  'Un buen encuadre respira, dejando espacio para que el ojo del espectador pueda pasear.',
  'La dirección de la mirada del sujeto guía invisiblemente la nuestra hacia el abismo.',
  'Fotografiar desde atrás es invitar al espectador a caminar junto al sujeto misterioso.',
  'La escala cromática afecta nuestra psique antes de que la razón pueda intervenir.',
  'El primer plano expone la vulnerabilidad, destruyendo la distancia segura de la objetividad.',
  'Un plano general sitúa al individuo frente a la inmensidad de su propio destino.',
  'El fuera de campo estimula la imaginación mucho más que la imagen más explícita.',
  'Una mirada periférica a menudo capta las verdades que el enfoque central intenta ocultar.',
  'El acto de mirar es en sí mismo una forma de posesión temporal y pacífica.',
  'Las líneas convergentes dirigen la mirada humana hacia el inevitable final del viaje.',
  'Un horizonte inclinado genera una inquietud visceral que ninguna palabra puede lograr calmar.',
  'La nitidez extrema a veces destruye el misterio fundamental que hace poética a una imagen.',
  'El desenfoque no es un error, es la representación visual de la incertidumbre humana.',
  'La forma en que se distribuyen las masas en la imagen refleja nuestro equilibrio mental.',
  'Una buena composición te atrapa, pero una composición magistral te transforma para siempre.',
  'Mirar a través del cristal es aceptar que siempre seremos observadores del mundo fugaz.',

  // --- Grupo 2: La Luz y la Oscuridad ---
  'La sombra da volumen a la luz y profundidad a nuestra propia existencia terrenal.',
  'Sin oscuridad, la luz pierde su capacidad de revelar los secretos del universo.',
  'La fotografía es literalmente la escritura con luz sobre el lienzo del tiempo.',
  'Un rayo de luz en la penumbra es un grito de esperanza visualmente innegable.',
  'La luz dura revela verdades ásperas, mientras que la luz suave acaricia las mentiras.',
  'El contraluz nos arrebata los detalles para regalarnos la esencia pura de la forma.',
  'La hora dorada no es solo luz, es la nostalgia del sol despidiéndose del día.',
  'La hora azul sumerge al mundo en una melancolía que la lente sabe comprender.',
  'Exponer correctamente es decidir matemáticamente cuánta verdad estás dispuesto a mostrar al mundo.',
  'La subexposición es el arte de dejar que el misterio consuma parte de la imagen.',
  'La sobreexposición borra las texturas, acercando la imagen a la pureza absoluta del blanco.',
  'El rango dinámico del ojo humano supera al sensor, pero la cámara perdona menos.',
  'Las sombras arrojadas cuentan historias paralelas a las de los objetos que las proyectan.',
  'La luz artificial intenta domar la noche, pero siempre deja rincones inexplorados y oscuros.',
  'El destello de un flash congela violentamente una fracción de segundo robada a la oscuridad.',
  'La luz difusa abraza al sujeto, eliminando las fronteras duras entre el ser y el espacio.',
  'Una silueta anónima se convierte en el recipiente perfecto para proyectar nuestras propias historias.',
  'El claroscuro fotográfico es la representación exacta de la dualidad moral del ser humano.',
  'La luz natural es caprichosa e indomable, exigiendo humildad a quien intenta registrarla.',
  'Medir la luz es sopesar la energía visible que rebota en nuestra realidad inmediata.',
  'El balance de blancos ajusta la temperatura de la imagen al clima de nuestras emociones.',
  'Una fotografía en blanco y negro destila la realidad eliminando la distracción del color.',
  'El gris medio es el punto de equilibrio donde la luz y la sombra firman la paz.',
  'La luz cenital aplasta al sujeto contra el suelo, sometiéndolo a la gravedad visual.',
  'La luz lateral revela las heridas del tiempo en la textura de cada superficie.',
  'La luz frontal aplana el rostro, mostrándolo desprovisto de secretos, desnudo ante el mundo.',
  'Los reflejos en el agua son la pintura impresionista que la naturaleza nos regala diariamente.',
  'Un destello en el lente (flare) nos recuerda la presencia ineludible del cristal observador.',
  'El contraste tonal separa los elementos dramáticamente, creando un teatro de sombras y luces.',
  'La luz pinta el paisaje, pero es el tiempo quien decide cuándo secar la pintura.',
  'En la penumbra, el sensor fotográfico busca desesperadamente la información que nuestros ojos ignoran.',
  'La luz que entra por una ventana es un puente entre el aislamiento y el exterior.',
  'Capturar la neblina es fotografiar la humedad suspendida en un abrazo de luz suave.',
  'El ruido digital en la oscuridad es el esfuerzo de la máquina por ver lo invisible.',
  'La saturación del color grita, mientras que la desaturación susurra historias mucho más íntimas.',
  'El rojo en el encuadre atrae la mirada humana con la urgencia del fuego primitivo.',
  'La luz reflejada nunca miente, solo adapta la verdad a la superficie que la proyecta.',
  'Una sombra alargada al atardecer es la memoria de un objeto que se niega a desaparecer.',
  'La ausencia de luz no es la nada, es el lienzo esperando ser iluminado.',
  'Pintar con luz en una larga exposición es coreografiar el movimiento en absoluta oscuridad.',
  'La iluminación de tres puntos es la trinidad clásica que construye la ilusión tridimensional.',
  'El halo de luz alrededor de un sujeto es la santificación laica de lo ordinario.',
  'La luz de la luna ofrece una paleta espectral que despierta nuestros sueños más profundos.',
  'El neón en las calles mojadas transforma la ciudad en un escenario cibernético de soledad.',
  'Aislar un sujeto con luz es otorgarle una importancia que la realidad le había negado.',
  'La clave alta respira optimismo y pureza, borrando los pesos terrenales de la imagen.',
  'La clave baja envuelve la escena en un dramatismo que ahoga cualquier intento de ligereza.',
  'El color dominante en una escena dicta la frecuencia emocional de todo el encuadre.',
  'La luz filtrada a través de las hojas crea un lenguaje codificado sobre el suelo.',
  'Ver la luz antes de ver el objeto es el primer mandamiento del creador audiovisual.',
  'La fotografía estenopeica nos recuerda que la luz siempre encuentra un camino para entrar.',
  'La luminancia de una imagen es la energía vital que la separa de la simple mancha.',

  // --- Grupo 3: El Tiempo y la Eternidad ---
  'Congelar el movimiento es descubrir la eternidad escondida en una pequeña fracción de segundo.',
  'La velocidad de obturación es la herramienta para manipular la percepción humana del tiempo transcurrido.',
  'Una larga exposición derrite el movimiento, convirtiendo a las multitudes en ríos de fantasmas.',
  'La fotografía es la única máquina del tiempo que el ser humano ha logrado construir.',
  'El tiempo expuesto en el sensor es un fragmento de vida arrancado del flujo constante.',
  'Un time-lapse nos permite ver la danza imperceptible de la naturaleza a escala cósmica.',
  'Cámara lenta no es alterar el tiempo, es prestarle atención a sus detalles más ocultos.',
  'Cada clic del obturador es una pequeña muerte y un nacimiento simultáneo de la memoria.',
  'El desenfoque de movimiento demuestra visualmente que nada en este universo permanece estático jamás.',
  'La fotografía detiene el tiempo para que el ojo humano pueda por fin comprenderlo.',
  'El cine fluye como un río, la fotografía es un bloque de hielo extraído de él.',
  'Al capturar un instante fugaz, lo condenamos a vivir eternamente en la inmovilidad absoluta.',
  'La obsolescencia de los objetos fotografiados nos recuerda nuestra propia e ineludible fecha de caducidad.',
  'Las arrugas en un retrato no son marcas, son mapas del tiempo pacientemente cartografiados.',
  'La sincronización de la cortinilla es el latido mecánico que define el principio y fin.',
  'Una ráfaga de fotos fragmenta el tiempo en pequeños cubos de realidad fácilmente digeribles.',
  'El barrido (panning) conecta la velocidad del sujeto con la atención del fotógrafo observador.',
  'La historia de la fotografía es la crónica de la humanidad intentando aferrarse al presente.',
  'Una imagen envejecida porta dos tiempos: el momento capturado y los años que la desgastaron.',
  'El instante decisivo de Cartier-Bresson es la alineación cósmica entre el evento y el ojo.',
  'Detener una gota en el aire es desafiar visualmente la ley física de la gravedad.',
  'En un hiperlapso, el espacio se comprime mientras el tiempo se acelera de forma vertiginosa.',
  'El retraso del obturador a veces nos regala un momento mejor del que habíamos planeado.',
  'La doble exposición colapsa dos tiempos diferentes en un mismo espacio de existencia visual.',
  'El revelado lento de una Polaroid es la materialización casi mágica del tiempo transcurrido.',
  'La persistencia retiniana engaña al cerebro para que el tiempo fragmentado parezca movimiento continuo.',
  'Una exposición prolongada de las estrellas evidencia que vivimos sobre una esfera en rotación constante.',
  'La cronofotografía nos enseñó a descomponer la anatomía del movimiento antes que el cine existiera.',
  'El parpadeo en el cine antiguo es el latido visual de una época ya perdida.',
  'Capturar la anticipación de un acto es atrapar el futuro antes de que se manifieste.',
  'El tiempo fotográfico es subjetivo: un segundo puede ser eterno o simplemente insuficiente.',
  'Fotografiar ruinas es hacer chocar el peso de la historia contra la ligereza del presente.',
  'El montaje cinematográfico es la escultura del tiempo tallada directamente sobre la atención humana.',
  'Un salto de eje temporal en video nos desorienta, recordándonos la fragilidad de la cronología.',
  'La cámara rápida hace que la tragedia humana parezca una coreografía cómica y diminuta.',
  'Congelar un salto es crear un momento de levitación que la realidad no puede sostener.',
  'El instante antes del beso es siempre más poderoso que el beso mismo inmortalizado.',
  'Capturar la decadencia de una flor es documentar el lento pero implacable paso del tiempo.',
  'La sincronización del flash a la segunda cortinilla deja un rastro visual del pasado inmediato.',
  'El pasado no existe en la fotografía, solo hay un presente que se niega a morir.',
  'Observar una vieja película familiar es invocar fantasmas que ríen ajenos a su propia mortalidad.',
  'El obturador parpadea más rápido que el ojo, pero retiene la memoria mucho más tiempo.',
  'El rastro de luces de los coches convierte el movimiento urbano en venas de energía pura.',
  'La temporalidad en la imagen estática es una ilusión creada por el contexto visual.',
  'La transición de un plano a otro en video marca el paso invisible del tiempo narrativo.',
  'El plano secuencia es el respeto máximo por el flujo ininterrumpido del tiempo real vivido.',
  'Cada fotografía analógica es un objeto físico marcado por el tiempo químico y la luz.',
  'La velocidad de fotogramas por segundo dicta si percibimos la obra como cine o videojuego.',
  'El tiempo de reacción del fotógrafo determina si la historia se cuenta o se pierde para siempre.',
  'Inmortalizar a un recién nacido es establecer el punto cero de una nueva cronología vital.',
  'La paciencia es el filtro más importante que un creador puede colocar frente a su lente.',
  'Fotografiar un reloj detiene las manecillas, pero no el tic-tac que resuena en nuestra mente.',

  // --- Grupo 4: El Sonido, el Silencio y el Ritmo Audiovisual ---
  'Escuchar el silencio en una escena es el primer paso para comprender su resonancia visual.',
  'Un sonido bien capturado tiene el poder de transportarnos a lugares que nunca hemos visitado.',
  'El cine no es imagen en movimiento, es la danza perfecta entre luces y frecuencias sonoras.',
  'El silencio absoluto en video genera más tensión que la banda sonora más estridente.',
  'El sonido ambiente es el tejido invisible que une al espectador con la escena mostrada.',
  'Un micrófono oculto escucha verdades que la cámara a menudo es incapaz de registrar visualmente.',
  'El efecto Foley nos demuestra que la verdad sonora en el cine es una hermosa mentira.',
  'El ritmo de montaje debe seguir el latido interno del corazón de la propia escena.',
  'La banda sonora no debe ilustrar la imagen, sino revelar su estado psicológico subyacente.',
  'El sonido fuera de campo amplía el universo narrativo sin necesidad de construir más decorados.',
  'Una voz en off es el pensamiento intrusivo que acompaña al espectador durante el viaje.',
  'El silencio entre los diálogos es donde residen los verdaderos sentimientos de los personajes.',
  'Desincronizar sutilmente el audio y el video causa una ruptura psicológica en el espectador atento.',
  'El estruendo repentino tras el silencio es una agresión estética calculada para despertar emociones.',
  'La reverberación de una sala vacía nos cuenta la historia de quienes ya se fueron.',
  'El sonido del obturador es el golpe de martillo que sentencia la eternidad de un instante.',
  'La música diegética ancla la escena a la realidad física que habitan los propios personajes.',
  'Un corte de audio abrupto te devuelve bruscamente a tu propia realidad física del asiento.',
  'El paisaje sonoro de una ciudad documenta su alma de manera más fiel que su arquitectura.',
  'Cerrar los ojos durante una película revela la arquitectura sonora que sostiene toda la ilusión.',
  'El susurro grabado de cerca resulta más íntimo y perturbador que el grito más desgarrador.',
  'El viento rozando el micrófono nos recuerda que la naturaleza no siempre quiere ser documentada.',
  'La ausencia de ruido de fondo convierte la escena en un espacio hiperrealista y clínico.',
  'Las frecuencias graves resuenan en el pecho antes de que el cerebro procese el significado visual.',
  'El tempo de la edición musical dicta la velocidad a la que el espectador respira inconscientemente.',
  'Un fundido a negro sonoro es la forma más elegante de sumergir al público en la incertidumbre.',
  'El solapamiento de diálogos imita el caos natural de la comunicación humana en la vida real.',
  'La fidelidad del sonido importa menos que la emoción cruda que es capaz de transmitir.',
  'El zumbido de un tubo fluorescente añade una ansiedad residual a cualquier escena aparentemente tranquila.',
  'Escuchar el clic de una cámara analógica es retroceder en el tiempo a través del oído.',
  'La compresión de audio aplasta los matices de la misma forma que el contraste excesivo.',
  'El sonido de unos pasos acercándose construye la anticipación mucho antes de mostrar al caminante.',
  'El eco espacial no solo repite el sonido, también multiplica la sensación de profunda soledad.',
  'El contraste entre sonido fuerte y suave es el equivalente auditivo del claroscuro en fotografía.',
  'Las texturas sonoras rugosas complementan las imágenes de entornos hostiles y decadentes sin requerir explicaciones.',
  'La mezcla de audio es el fino arte de decidir qué frecuencias tienen derecho a existir.',
  'Un grito inaudible en pantalla es la máxima representación visual de la impotencia humana absoluta.',
  'La polifonía en el cine permite que múltiples narrativas coexistan en el mismo espacio y tiempo.',
  'El rango dinámico del audio determina la distancia emocional entre un susurro y una explosión.',
  'El diseño sonoro construye un mundo tridimensional que la pantalla plana no puede contener físicamente.',
  'El crujido de la película de 16mm añade una capa táctil a la experiencia de visualización.',
  'Un pitido continuo aísla al personaje y lo encierra en su propio colapso mental inminente.',
  'La espacialidad del sonido envolvente rompe las barreras físicas de la sala de proyección tradicional.',
  'El silencio compartido entre dos personajes puede ser el diálogo más ruidoso de la película.',
  'El zumbido de una cinta magnética contiene la huella analógica de una época tecnológica pasada.',
  'Un sonido discordante destruye la armonía visual para obligar al cerebro a prestar atención nuevamente.',
  'La rima visual encuentra su eco más profundo cuando está respaldada por un motivo sonoro recurrente.',
  'El diseño de sonido no se escucha, se siente en los huesos a través de la vibración.',
  'La reverberación del pasado resuena en las imágenes antiguas, aunque carezcan de audio perceptible.',
  'Un corte sonoro (J-cut o L-cut) sutura dos escenas diferentes creando una continuidad mental perfecta.',
  'La cacofonía sonora refleja el estado de un mundo moderno que ha olvidado cómo escuchar.',
  'El crujido de la nieve bajo los pies hace que la imagen en pantalla transmita frío literal.',

  // --- Grupo 5: La Realidad, la Verdad y la Ficción ---
  'El lente de la cámara actúa como un puente entre la realidad objetiva y nuestra imaginación.',
  'Una fotografía miente siempre, pero en esa mentira a menudo revela una verdad mucho más profunda.',
  'El cine es la verdad a veinticuatro cuadros por segundo luchando contra su propia ficción.',
  'La manipulación digital solo expone visualmente las manipulaciones mentales que el cerebro ya ha realizado.',
  'El documental no refleja la realidad, refleja el punto de vista humano sobre la realidad.',
  'Cualquier encuadre excluye el contexto, convirtiendo la verdad capturada en una narrativa altamente maleable.',
  'La luz proyectada en la sala de cine es una ilusión que elegimos creer colectivamente.',
  'Una imagen sin retocar no es más real, simplemente tiene un tipo diferente de procesamiento algorítmico.',
  'El fotoperiodismo busca la objetividad, pero siempre está filtrado por la empatía o el sesgo.',
  'La postproducción no salva una mala idea, solo disfraza la falta de intención creativa inicial.',
  'El surrealismo visual nace cuando las reglas de la luz chocan con la irracionalidad del sueño.',
  'La cámara actúa como un escudo protector frente a una realidad que resulta demasiado abrumadora.',
  'Fotografiar un paisaje es intentar poseer un espacio que la naturaleza nunca nos ha cedido.',
  'La edición convierte imágenes inconexas en un silogismo visual que empuja al espectador a concluir.',
  'Un efecto especial práctico envejece mejor porque estuvo atado a las leyes de la física.',
  'El archivo RAW contiene todas las verdades posibles antes de que el fotógrafo tome una decisión.',
  'La saturación excesiva es el intento desesperado de hacer que la realidad parezca más emocionante.',
  'Un actor frente a la lente debe dejar de actuar y empezar simplemente a ser observado.',
  'La fotografía de calle es el arte de robar instantes de autenticidad en un mundo artificial.',
  'El croma verde es el lienzo en blanco del siglo veintiuno, esperando ser llenado de mundos.',
  'Un reflejo en un escaparate superpone dos realidades que de otro modo nunca podrían tocarse.',
  'La autenticidad fotográfica no reside en la técnica pura, sino en la honestidad del autor.',
  'El error técnico (glitch) rompe la ilusión digital y nos recuerda la fragilidad del medio.',
  'La sobreexposición mediática anestesia al espectador, convirtiendo la tragedia real en ruido visual ignorado.',
  'El metacine nos recuerda que detrás de cada historia hay un equipo operando las luces.',
  'La inteligencia artificial generando imágenes desafía nuestra noción más básica de lo que constituye memoria.',
  'Un holograma carece de sombra real, evidenciando su condición de fantasma hecho de luz pura.',
  'El fotomontaje une pedazos rotos del mundo para construir una utopía o una pesadilla coherente.',
  'La resolución 8K ofrece más detalles de los que el cerebro necesita para experimentar la emoción.',
  'Un filtro de redes sociales enmascara la realidad, construyendo avatares de perfección inalcanzable y vacía.',
  'El objetivo ojo de pez curva la arquitectura recta, distorsionando la seguridad de nuestro entorno habitual.',
  'La censura visual recortando una imagen altera la historia de forma más violenta que reescribirla.',
  'Un maniquí en un escaparate fotografiado de noche parece más humano que la multitud diurna.',
  'El fotorrealismo en 3D persigue la imperfección porque en la perfección absoluta habitan las máquinas.',
  'El valle inquietante (uncanny valley) es el rechazo visceral de la mirada hacia lo artificialmente casi-humano.',
  'La realidad virtual nos aísla físicamente para sumergirnos por completo en un entorno inmaterial interactivo.',
  'Un atrezzo bien iluminado engaña al espectador para que acepte cartón piedra como mármol sólido.',
  'La distorsión del cristal antiguo deforma la imagen, añadiendo el peso del tiempo a la vista.',
  'El color de la memoria rara vez coincide exactamente con el código hexadecimal de la fotografía.',
  'El arte del maquillaje para cine consiste en simular la naturalidad frente a luces antinaturales intensas.',
  'Una imagen borrosa del monstruo siempre da más miedo que el monstruo enfocado e hiperdetallado.',
  'La escala de un decorado en miniatura engaña al cerebro solo si la perspectiva es matemáticamente perfecta.',
  'El falso documental (mockumentary) explota nuestra fe ciega en el formato estético del reportaje periodístico.',
  'Una cámara de seguridad registra la realidad objetiva sin ninguna piedad narrativa ni filtro empático.',
  'El metraje encontrado (found footage) nos obliga a convertirnos en detectives de una tragedia visual inminente.',
  'La refracción a través de un prisma descompone la luz en el espectro oculto de la realidad visible.',
  'Un espejo roto multiplica el sujeto fotografiado, fragmentando su identidad en decenas de astillas cortantes.',
  'La gradación de color (color grading) reescribe la psicología de la escena desde la postproducción fría.',
  'Una sombra proyectada engañosa puede hacer creer al espectador que el peligro inminente es colosal.',
  'La hiperrealidad satura tanto los sentidos que la verdadera naturaleza externa comienza a parecer descolorida.',
  'El arte abstracto fotográfico renuncia al significado literal para abrazar directamente el impacto puramente sensorial.',
  'Un rostro iluminado por una pantalla en la oscuridad es el retrato icónico del hombre moderno.',

  // --- Grupo 6: El Movimiento, el Flujo y la Transición ---
  'Cada fotograma de una película respira sutilmente con la vida de quienes lo han imaginado pacientemente.',
  'El travelling físico desplaza el punto de vista acercándonos al corazón emocional de la escena retratada.',
  'El movimiento de cámara en mano transmite la inestabilidad emocional directa del operador al espectador.',
  'Un zoom digital destruye la intimidad, acercando los píxeles sin realmente acortar la distancia física.',
  'El vértigo (Dolly Zoom) estira el espacio manteniendo al sujeto anclado, desmoronando la realidad visual circundante.',
  'La steadycam nos otorga el privilegio de flotar como entidades omniscientes sin peso gravitacional aparente.',
  'La panorámica revela el espacio gradualmente, postergando la resolución del misterio oculto en el paisaje.',
  'La cadencia de la caminata de un personaje dicta el ritmo interno de toda la secuencia rítmica.',
  'El movimiento cinético de una bailarina exige que la cámara baile con ella en perfecta armonía.',
  'La inmovilidad total del cuadro subraya el impacto devastador de cualquier mínimo movimiento repentino interno.',
  'Un corte de salto (jump cut) fractura el tiempo continuo, acelerando la ansiedad del momento documentado.',
  'La transición de barrido difumina el límite entre dos mundos, fusionándolos en un solo golpe visual.',
  'El flujo visual de derecha a izquierda se percibe inconscientemente como una resistencia antinatural al avance.',
  'El encuadre holandés desestabiliza el eje de la tierra, sugiriendo que el mundo narrativo está colapsando.',
  'Un plano secuencia sin cortes exige que la realidad fluya sin la red de seguridad del montaje.',
  'La dirección de movimiento de los personajes guía al ojo humano como un dedo apuntando firmemente.',
  'El rastro estelar cruzando el cielo nocturno evidencia visualmente que estamos viajando a gran velocidad cósmica.',
  'Una cámara anclada a un vehículo nos sumerge en un túnel de visión dinámica e imparable.',
  'El stop-motion dota de alma al plástico inerte mediante la magia artesanal del cambio microscópico milimétrico.',
  'La rotoscopia persigue el movimiento humano realista calcando la vida real sobre fotogramas dibujados laboriosamente.',
  'El tracking lateral acompaña al sujeto a través del espacio, mostrando su entorno sin perderlo de vista.',
  'La grúa cinematográfica eleva nuestra perspectiva, despegándonos del suelo para alcanzar una visión celestial abarcadora.',
  'Un paneo rápido (whip pan) desorienta momentáneamente al espectador, inyectando adrenalina cruda en la transición visual.',
  'La fluidez de los 60 cuadros por segundo hiperrealiza el movimiento, restándole la magia del desenfoque cinemático.',
  'El movimiento oscilante del agua reflejado en una pared relaja la tensión visual de cualquier habitación cerrada.',
  'La cinemática es el lenguaje del movimiento codificado para maximizar el impacto emocional en el cerebro reptiliano.',
  'Un objeto cayendo en cámara lenta se convierte en un evento de contemplación poética casi religiosa.',
  'La aceleración de los cortes hacia el clímax aumenta la frecuencia cardíaca del público sin tocarlo.',
  'El movimiento circular alrededor del sujeto lo aísla del mundo, convirtiéndolo en el centro del universo inmediato.',
  'La falta de estabilización en un documental de guerra certifica la autenticidad del peligro inminente circundante.',
  'El viento moviendo los árboles en el fondo es el latido vital inconsciente de un plano fijo.',
  'Un encuadre estático que observa una puerta vacía genera la angustiosa expectativa narrativa de que alguien entrará.',
  'La transición por encadenado funde dos memorias temporales diferentes, indicando el paso melancólico del tiempo narrativo.',
  'El desvanecimiento a blanco sugiere una revelación espiritual o el borrado absoluto de la memoria acumulada.',
  'El travelling retroactivo (pull back) expande el contexto, revelando nuestra ignorancia previa sobre la situación mostrada.',
  'Un seguimiento desde atrás de un personaje transmite la sensación de destino inevitable o persecución latente.',
  'La cámara subjetiva obliga al espectador a habitar temporalmente la piel y los pecados del personaje principal.',
  'El movimiento de las nubes en un time-lapse revela los ríos atmosféricos invisibles que gobiernan el clima.',
  'La acción paralela cruza dos destinos diferentes mediante el ritmo frenético del montaje convergente hacia el clímax.',
  'El movimiento desordenado de una multitud desenfocada expresa la alineación urbana de la época moderna.',
  'Una chispa volando por el aire tiene la duración exacta de una vida humana a escala atómica.',
  'El giro vertiginoso de una noria fotografiada a baja velocidad es un mandala de pura luz urbana.',
  'El tilt-up desde los pies hasta la cabeza presenta al personaje imponiendo respeto antes de cualquier diálogo hablado.',
  'El travelling óptico distorsiona el fondo mientras que el travelling físico respeta la geometría natural del espacio real.',
  'Un plano de seguimiento rápido entre los árboles simula el punto de vista del depredador acechando en silencio.',
  'El movimiento fluido de los gimbals modernos anestesia la textura física del terreno que se está pisando.',
  'La edición rítmica sincronizada con el golpe musical convierte el montaje en una percusión estrictamente visual.',
  'Un plano holandés extremo en movimiento provoca náuseas morales al reflejar la corrupción del ambiente retratado.',
  'La caída de las hojas en otoño grabada de cerca es el recordatorio visual de que nada perdura.',
  'El vaivén de un péndulo capturado cíclicamente hipnotiza al espectador robándole la noción del paso del tiempo.',
  'Un ligero temblor en la cámara rompe el aislamiento artificial del equipo y lo humaniza al instante.',
  'El movimiento del sol alterando las sombras durante horas altera el significado de toda la arquitectura grabada.',

  // --- Grupo 7: La Memoria, la Emoción y el Residente Físico ---
  'La luz no solo ilumina objetos, también revela la textura invisible de nuestros recuerdos más profundos anclados.',
  'Una fotografía vieja es un mapa mudo que nos guía hacia personas que ya no somos nosotros.',
  'El álbum fotográfico familiar es la arquitectura emocional donde almacenamos la prueba de que fuimos amados.',
  'La nostalgia no está en la imagen, está en la mente del que observa la imagen desgastada.',
  'Destruir una fotografía es cometer un pequeño asesinato simbólico contra la memoria de un instante pasado.',
  'El polvo acumulado sobre una diapositiva es el rastro geológico del olvido que amenaza al recuerdo almacenado.',
  'Una imagen sobreexpuesta hasta quedar blanca es la representación gráfica del olvido consumiendo los detalles del pasado.',
  'Mirar las fotos de un desconocido es explorar las ruinas de una civilización que nunca hemos habitado.',
  'La cámara estenopeica hecha en casa captura imágenes utilizando la misma magia primitiva que habitaba las cavernas.',
  'El olor a químicos en el cuarto oscuro es el perfume inconfundible del recuerdo manifestándose físicamente sobre papel.',
  'El grano argéntico de la película tradicional es la textura orgánica del azar y la imperfección humana.',
  'Una imagen digital perfecta carece del alma rugosa que la emulsión química otorgaba al retrato del pasado.',
  'La copia física de una imagen es la resistencia tangible frente a la evaporación de los archivos digitales.',
  'El formato cuadrado recorta el mundo periférico para forzarnos a mirar directamente al corazón del asunto central.',
  'Una cicatriz fotografiada no es una herida, es el monumento sobreviviente de una batalla silenciosamente librada y ganada.',
  'El cianotipo tiñe el mundo de un azul melancólico, convirtiendo la luz del sol en sombras marinas congeladas.',
  'El sepia envejece prematuramente la imagen, inyectando artificialmente la pátina del tiempo en un instante muy reciente.',
  'Una sonrisa fingida frente al objetivo es la armadura emocional con la que nos protegemos del futuro espectador.',
  'La imagen de una cama vacía contiene más drama humano que la representación explícita de un duelo amargo.',
  'El cuarto oscuro no es un espacio físico, es un estado mental de revelación íntima y aislada.',
  'La gelatina de plata atrapa la luz usando la misma alquimia que utilizaban los antiguos para atrapar espíritus.',
  'Una fotografía olvidada en un cajón es un secreto que el tiempo mantiene congelado a la espera del descubrimiento.',
  'El archivo fotográfico mundial es el disco duro colectivo de una humanidad obsesionada con su propia trascendencia efímera.',
  'La sonrisa auténtica siempre alcanza los ojos y es imposible de engañar frente a un sensor fotográfico.',
  'El llanto capturado en silencio resuena visualmente mucho más fuerte que el sonido del dolor físico mismo.',
  'Fotografiar espacios abandonados es rendir homenaje a la memoria acústica de los pasos que alguna vez resonaron allí.',
  'La imagen borrosa de un fantasma no asusta por su claridad, asusta por lo que la mente completa.',
  'Una doble exposición no planeada es el subconsciente de la cámara revelando conexiones mágicas entre dos realidades separadas.',
  'El borde dentado de una copia vintage en papel añade un marco táctil al recuerdo impreso con amor.',
  'Guardar una foto en la cartera es la versión moderna del amuleto protector para enfrentarse al mundo hostil.',
  'La fotografía esteganográfica esconde mensajes secretos dentro de paisajes aparentemente inocentes a simple vista de extraños.',
  'El deterioro de la emulsión fílmica con hongos se asemeja biológicamente a las placas de la demencia senil.',
  'Una foto movida por el nerviosismo del fotógrafo contiene la emoción real de la adrenalina del momento tenso.',
  'La soledad retratada desde lejos es menos dolorosa que la soledad compartida en un primer plano asfixiante cercano.',
  'El abrazo final congelado en película es la negación absoluta de la separación inevitable que impone el tiempo.',
  'Fotografiar un objeto querido de la infancia es intentar recuperar el tamaño monumental que solía tener entonces.',
  'La memoria visual es frágil, por eso externalizamos el recuerdo en píxeles y químicos altamente fotosensibles al entorno.',
  'Un retrato rasgado por la mitad es el testimonio visual de una relación fracturada sin vuelta atrás posible.',
  'La subexposición del sujeto contra la ventana brillante refleja el conflicto entre el deseo interior y la obligación.',
  'El fotolibro es una narrativa lineal construida con piezas de rompecabezas emocionales cuidadosamente seleccionadas por el autor.',
  'El olor del proyector calentándose es el preludio pavloviano de la inmersión en la memoria colectiva cinematográfica.',
  'Fotografiar las nubes es intentar documentar la forma transitoria de nuestros propios pensamientos divagando en el cielo abierto.',
  'Una foto desenfocada del ser amado sigue siendo perfecta a los ojos del que comprende la intención inicial.',
  'El reflejo distorsionado en el espejo retrovisor es la mirada nostálgica hacia el camino que acabamos de dejar.',
  'La placa de cristal fotográfica es pesada y frágil, exactamente como los recuerdos que intenta preservar celosamente.',
  'Un beso borroso en la lluvia es el clímax emocional de la memoria visual romántica moderna por excelencia.',
  'El proceso de escaneado de un negativo es la resurrección digital de un alma química enterrada en plata.',
  'La luz parpadeante del proyector Super 8 invoca los espectros luminosos de veranos familiares irremediablemente concluidos y lejanos.',
  'La imagen post-mortem victoriana intentaba negar la muerte otorgando a los caídos una última pose serena y artificial.',
  'Cada píxel dañado (dead pixel) es una pequeña herida incurable en el tejido digital de la representación moderna.',
  'La fotografía es el salvavidas visual que la memoria lanza al mar del tiempo para no terminar ahogándose.',
  'El último fotograma de una película marca el inicio inmediato del recuerdo que conservaremos para el resto de nuestras vidas.'
];

export function getDailyPhrase(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = (now.getTime() - start.getTime()) + ((start.getTimezoneOffset() - now.getTimezoneOffset()) * 60 * 1000);
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  // Return phrases cycling if the list is smaller than 366
  return dailyPhrases[dayOfYear % dailyPhrases.length];
}
